# Generated by Django 5.2.6 on 2025-09-26 00:03

import django.core.validators
import django.db.models.deletion
import symptoms.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', symptoms.models.custom_fields.LowerCaseCharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Symptom Categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Unknown', 'Unknown'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Unknown', max_length=8)),
                ('sex', models.CharField(choices=[('Unknown', 'Unknown'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Unknown', max_length=8)),
                ('birth_year', models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('race', models.CharField(blank=True, max_length=50, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('no_show', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='symptoms.client')),
            ],
            options={
                'verbose_name_plural': 'Client Sessions',
            },
        ),
        migrations.CreateModel(
            name='ClientSessionProtocolSiteTrainingAlphaTheta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('Unknown', 'Unknown')], default='Unknown', max_length=32)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('alpha_frequency_hertz', models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(40000)])),
                ('theta_frequency_hertz', models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(40000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsession')),
            ],
            options={
                'verbose_name_plural': 'Client Session Protocol Site Training - AlphaTheta',
            },
        ),
        migrations.CreateModel(
            name='ClientSessionProtocolSiteTrainingFrequencyBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('Unknown', 'Unknown')], default='Unknown', max_length=32)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('frequency_hertz', models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(40000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsession')),
            ],
            options={
                'verbose_name_plural': 'Client Session Protocol Site Training - FrequencyBand',
            },
        ),
        migrations.CreateModel(
            name='ClientSessionProtocolSiteTrainingILF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('Unknown', 'Unknown')], default='Unknown', max_length=32)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('frequency_millihertz', models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(40000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsession')),
            ],
            options={
                'verbose_name_plural': 'Client Session Protocol Site Training - ILF',
            },
        ),
        migrations.CreateModel(
            name='ClientSessionProtocolSiteTrainingSynchrony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(choices=[('Unknown', 'Unknown')], default='Unknown', max_length=32)),
                ('duration_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('frequency_millihertz', models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(40000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsession')),
            ],
            options={
                'verbose_name_plural': 'Client Session Protocol Site Training - Synchrony',
            },
        ),
        migrations.CreateModel(
            name='ClientSymptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('baseline_goodweek', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('baseline_badweek', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('baseline_usualweek', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.client')),
                ('symptom_categories', models.ManyToManyField(to='symptoms.symptomcategory')),
            ],
            options={
                'verbose_name_plural': 'Client Symptoms',
                'unique_together': {('client', 'description')},
            },
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Therapists',
            },
        ),
        migrations.AddField(
            model_name='clientsession',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.therapist'),
        ),
        migrations.CreateModel(
            name='ClientNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.client')),
                ('therapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.therapist')),
            ],
            options={
                'verbose_name_plural': 'Client Notes',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='therapist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.therapist'),
        ),
        migrations.CreateModel(
            name='ClientSessionSymptomScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsession')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptoms.clientsymptom')),
            ],
            options={
                'verbose_name_plural': 'Client Session Symptom Scores',
                'unique_together': {('session', 'symptom')},
            },
        ),
    ]
