# Generated by Django 5.2.6 on 2025-09-26 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientsessionprotocolsitetrainingalphatheta',
            options={'verbose_name': 'Session Protocol Site - AlphaTheta', 'verbose_name_plural': 'Session Protocol Site - AlphaTheta'},
        ),
        migrations.AlterModelOptions(
            name='clientsessionprotocolsitetrainingfrequencyband',
            options={'verbose_name': 'Session Protocol Site - FrequencyBand', 'verbose_name_plural': 'Session Protocol Site - FrequencyBand'},
        ),
        migrations.AlterModelOptions(
            name='clientsessionprotocolsitetrainingilf',
            options={'verbose_name': 'Session Protocol Site - ILF', 'verbose_name_plural': 'Session Protocol Site - ILF'},
        ),
        migrations.AlterModelOptions(
            name='clientsessionprotocolsitetrainingsynchrony',
            options={'verbose_name': 'Session Protocol Site - Synchrony', 'verbose_name_plural': 'Session Protocol Site - Synchrony'},
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='duration_minutes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
