# Generated by Django 5.2.6 on 2025-10-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_alter_client_id_alter_clientsession_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientnote',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
