# Generated by Django 5.2.6 on 2025-10-10 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_alter_clientnote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsession',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='symptoms.therapist'),
        ),
    ]
