# Generated by Django 5.2.6 on 2025-10-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_alter_clientsession_therapist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientsession',
            unique_together={('client', 'date')},
        ),
    ]
