# Generated by Django 5.2.6 on 2025-10-10 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0006_alter_clientsession_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientsession',
            unique_together=set(),
        ),
    ]
