# Generated by Django 5.2.6 on 2025-10-23 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0007_alter_clientsession_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='alpha_frequency_hertz',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(8.0), django.core.validators.MaxValueValidator(13.0)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='theta_frequency_hertz',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(3.5), django.core.validators.MaxValueValidator(7.9)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='frequency_hertz',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='frequency_millihertz',
            field=models.DecimalField(decimal_places=6, default=1e-06, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(1e-06), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='frequency_millihertz',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(0.05)]),
        ),
    ]
