# Generated by Django 5.2.6 on 2025-10-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0008_alter_clientsessionprotocolsitetrainingalphatheta_alpha_frequency_hertz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='site1',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='site2',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='site1',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='site2',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='site1',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='site2',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='site1',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='site2',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('A1', 'A1'), ('A2', 'A2'), ('C3', 'C3'), ('C4', 'C4'), ('Cz', 'Cz'), ('F3', 'F3'), ('F4', 'F4'), ('F7', 'F7'), ('F8', 'F8'), ('Fp1', 'Fp1'), ('Fp2', 'Fp2'), ('Fz', 'Fz'), ('O1', 'O1'), ('O2', 'O2'), ('P3', 'P3'), ('P4', 'P4'), ('Pz', 'Pz'), ('T3', 'T3'), ('T4', 'T4'), ('T5', 'T5'), ('T6', 'T6')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingalphatheta',
            name='site',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Fp1-Fp2', 'Fp1-Fp2'), ('T3-Fp1', 'T3-Fp1'), ('T3-P3', 'T3-P3'), ('T3-P4', 'T3-P4'), ('T3-T4', 'T3-T4'), ('T4-Fp2', 'T4-Fp2'), ('T4-P4', 'T4-P4')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingfrequencyband',
            name='site',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Fp1-Fp2', 'Fp1-Fp2'), ('T3-Fp1', 'T3-Fp1'), ('T3-P3', 'T3-P3'), ('T3-P4', 'T3-P4'), ('T3-T4', 'T3-T4'), ('T4-Fp2', 'T4-Fp2'), ('T4-P4', 'T4-P4')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingilf',
            name='site',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Fp1-Fp2', 'Fp1-Fp2'), ('T3-Fp1', 'T3-Fp1'), ('T3-P3', 'T3-P3'), ('T3-P4', 'T3-P4'), ('T3-T4', 'T3-T4'), ('T4-Fp2', 'T4-Fp2'), ('T4-P4', 'T4-P4')], default='Unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='clientsessionprotocolsitetrainingsynchrony',
            name='site',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Fp1-Fp2', 'Fp1-Fp2'), ('T3-Fp1', 'T3-Fp1'), ('T3-P3', 'T3-P3'), ('T3-P4', 'T3-P4'), ('T3-T4', 'T3-T4'), ('T4-Fp2', 'T4-Fp2'), ('T4-P4', 'T4-P4')], default='Unknown', max_length=32),
        ),
    ]
